site_name: New Project Provisioning
copyright: Copyright &copy; 2023 Civic Tech Structure

nav:
  - Home: index.md
  - MkDocs: mkdocs.md
  - License: license.md

theme:
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.sections

repo_url: https://github.com/hackforla/admin-new-project-provisioning
repo_name: hackforla/admin-new-project-provisioning
edit_uri: edit/main/docs/

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hackforla/admin-new-project-provisioning

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - toc:
      title: On this page
      permalink: true

  # PyMdown Extensions
  - pymdownx.betterem
  - pymdownx.blocks.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

watch:
  - README.md
  - LICENSE
